CREATE OR REPLACE FUNCTION public.pp_integrity_check()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare f jsonb := '[]'::jsonb; c jsonb := '{}'::jsonb; n bigint; t text; begin
  select count(*) into n from pp_scraper_signals where not is_legacy and signal_type='nts'; c := c || jsonb_build_object('live_nts', n); if n>0 then f := f || jsonb_build_object('check','no fake sale notices','count',n); end if;
  select count(*) into n from pp_agents where email ~* '@example\.|\.test$'; c := c || jsonb_build_object('test_agents', n); if n>0 then f := f || jsonb_build_object('check','no test agents','count',n); end if;
  select count(*) into n from pp_outcome_events e where not exists (select 1 from pp_agents a where a.user_id::text=e.actor or a.agent_id=e.actor); c := c || jsonb_build_object('orphan_outcomes', n); if n>0 then f := f || jsonb_build_object('check','every outcome has a real agent','count',n); end if;
  select count(*) into n from pp_lead_lifecycle l where not exists (select 1 from pp_outcome_events e where e.entity_key=l.entity_key); c := c || jsonb_build_object('lifecycle_without_events', n); if n>0 then f := f || jsonb_build_object('check','lifecycle rows have events','count',n); end if;
  select count(*) into n from pp_scraper_signals where not is_legacy and raw_owner_name ~* '\m(TEST|SAMPLE|DEMO|FAKE|DUMMY|PLACEHOLDER|LOREM)\M'; c := c || jsonb_build_object('placeholder_names', n); if n>0 then f := f || jsonb_build_object('check','no placeholder names','count',n); end if;
  select count(*) into n from pp_scraper_signals where not is_legacy and source_slug in ('slco-recorder-live','comparable-sales-slco') and county<>'Utah'; c := c || jsonb_build_object('mislabelled_county', n); if n>0 then f := f || jsonb_build_object('check','Utah-endpoint rows labelled Utah','count',n); end if;
  select count(*) into n from pp_scraper_signals where not is_legacy and signal_type='nod' and county='Utah' and pp_payload(raw_payload)->>'koi' not in ('ND'); c := c || jsonb_build_object('utah_nod_wrong_kind', n); if n>0 then f := f || jsonb_build_object('check','Utah NOD rows are kind ND','count',n); end if;
  select count(*) into n from pp_scraper_signals where not is_legacy and signal_type='divorce_filing' and (raw_payload::text ilike '%custody%' or raw_payload::text ilike '%paternity%' or raw_payload::text ilike '%protective%'); c := c || jsonb_build_object('divorce_misclass', n); if n>0 then f := f || jsonb_build_object('check','divorces are divorces','count',n); end if;
  select count(*) into n from pp_conviction_queue q where not exists (select 1 from pp_scraper_signals s where s.owner_key=q.entity_key and not s.is_legacy and not s.is_institutional); c := c || jsonb_build_object('queue_without_signal', n); if n>0 then f := f || jsonb_build_object('check','every queue lead has a live signal','count',n); end if;
  select count(*) into n from pp_conviction_queue where max_stage=5; c := c || jsonb_build_object('stage5', n); if n>0 then f := f || jsonb_build_object('check','no auction stage without a sale notice source','count',n); end if;
  select count(*) into n from pp_conviction_queue where owner_display ~* '\m(BANK|MORTGAGE|SERVICING|LENDING|FEDERAL|CREDIT UNION|MERS)\M'; c := c || jsonb_build_object('lenders_in_queue', n); if n>0 then f := f || jsonb_build_object('check','no lenders in the queue','count',n); end if;
  select count(*) into n from pp_conviction_queue where conviction_score > 65 and not property_confirmed; c := c || jsonb_build_object('unconfirmed_above_65', n); if n>0 then f := f || jsonb_build_object('check','no lead above 65 without a property tie','count',n); end if;
  select count(*) into n from pp_buyer_intel b where purchases > (select count(distinct regexp_replace(coalesce(pp_payload(s.raw_payload)->>'entry', s.raw_address),'[[:space:]\u00a0]+',' ','g')) from pp_scraper_signals s where not s.is_legacy and s.signal_type in ('deed_transfer','comparable_sale') and 'B:'||pp_norm(pp_payload(s.raw_payload)->>'grantee') = b.buyer_key); c := c || jsonb_build_object('buyers_overcounted', n); if n>0 then f := f || jsonb_build_object('check','buyer purchases are distinct documents','count',n); end if;
  select count(*) into n from pp_buyer_intel where buyer_display ~* '\m(BANK|MORTGAGE|SERVICING|LENDING|FEDERAL|CREDIT UNION|MERS|TITLE|ESCROW)\M'; c := c || jsonb_build_object('lenders_as_buyers', n); if n>0 then f := f || jsonb_build_object('check','no lenders or title companies as buyers','count',n); end if;
  select count(*) into n from pp_buyer_intel b where not b.is_move_up and not exists (select 1 from pp_buyer_signals s where s.buyer_key=b.buyer_key and s.signal_type='purchase'); c := c || jsonb_build_object('buyers_without_deed', n); if n>0 then f := f || jsonb_build_object('check','every recorded buyer has a warranty-deed purchase signal','count',n); end if;
  select count(*) into n from pp_buyer_intel b where b.is_move_up and (b.sold_entry is null or pp_is_institutional(b.buyer_display) or not exists (select 1 from pp_buyer_signals s where s.buyer_key=b.buyer_key and s.signal_type='move_up')); c := c || jsonb_build_object('moveup_without_sale', n); if n>0 then f := f || jsonb_build_object('check','every move-up buyer rests on a recorded sale','count',n); end if;
  select count(*) into n from pp_buyer_intel b where b.cash_purchases>0 and not (b.counties && (select coalesce(array_agg(county),'{}') from (select county from pp_scraper_signals where not is_legacy and signal_type in ('deed_of_trust','deed_transfer') group by county, source_slug having count(*) filter (where signal_type='deed_of_trust')>0 and count(*) filter (where signal_type='deed_transfer')>0) cov)); c := c || jsonb_build_object('cash_without_coverage', n); if n>0 then f := f || jsonb_build_object('check','cash is only inferred where trust-deed coverage is complete','count',n); end if;
  select count(*) into n from pp_buyer_intel where buyer_display ~* '\m(TEST|SAMPLE|DEMO|FAKE|DUMMY|LOREM)\M'; c := c || jsonb_build_object('placeholder_buyers', n); if n>0 then f := f || jsonb_build_object('check','no placeholder buyer names','count',n); end if;
  select count(*) into n from pp_buyer_leads l where not exists (select 1 from pp_agents a where a.agent_id=l.agent_id and a.active); c := c || jsonb_build_object('orphan_buyer_leads', n); if n>0 then f := f || jsonb_build_object('check','every captured buyer lead belongs to a registered agent','count',n); end if;
  select count(*) into n from pp_buyer_intel where computed_at < now()-interval '36 hours'; c := c || jsonb_build_object('buyers_stale', n); if n>0 then f := f || jsonb_build_object('check','buyer intelligence recomputed nightly','count',n); end if;
  select string_agg(source_slug, ', ') into t from (
    select source_slug from pp_run_log where run_at>now()-interval '37 days'
      and source_slug <> 'utah-county-tax-delinquency-pdf'  -- county republishes on its own schedule; checked for reachability + parse in integrity_spotcheck.py instead
    group by 1
    having max(run_at) > now()-interval '20 hours'  -- still in the daily run (retired sources drop out)
       and sum(signal_count) filter (where run_at between now()-interval '37 days' and now()-interval '7 days') > 0
       and sum(signal_count) filter (where run_at > now()-interval '7 days') = 0) x;
  c := c || jsonb_build_object('registered_sources_gone_quiet', coalesce(t,'')); if t is not null then f := f || jsonb_build_object('check','registered sources still producing','sources',t); end if;
  insert into pp_integrity_log(passed, failures, checked) values (jsonb_array_length(f)=0, f, c);
  return jsonb_build_object('passed', jsonb_array_length(f)=0, 'failures', f, 'checked', c);
end $function$
